# ARCS6 サブMakefile
# 2024/08/01 Yokokura, Yuki

# ARCSシステムディレクトリへのパス（このMakefileから見た相対パス）
SYSPATH = ../../../sys

# 追加のコンパイル済み中間ファイル（このMakefileから見た相対パス）
ADDOBJ =

# メインMakefileの読み込み
include $(SYSPATH)/Makefile
